repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: behave-format
        name: behave-format
        entry: behave-format
        language: system
        files: \.feature$
        pass_filenames: true
